name: Build and Release Debian Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libcurl4-openssl-dev libcjson-dev dpkg-dev

      - name: Build binary
        run: gcc aslookup.c -o aslookup -lcurl -lcjson -lresolv

      - name: Prepare .deb package structure
        run: |
          mkdir -p pkg/usr/local/bin
          cp aslookup pkg/usr/local/bin/
          mkdir -p pkg/DEBIAN
          cat <<EOF > pkg/DEBIAN/control
          Package: aslookup
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Maintainer: Your Name <your@email.com>
          Description: ASN lookup utility
          Depends: libc6, libcurl4, libcjson1
          EOF

      - name: Build .deb package
        run: dpkg-deb --build pkg aslookup_1.0_amd64.deb

      - name: Upload .deb to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: aslookup_1.0_amd64.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
