name: Build, Compile and Release C Program

on:
  push:
    tags:
      - '*'  # Triggers on any tag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Download C source file
      run: curl -o aslookup.c https://raw.githubusercontent.com/nieldk/aslookup/refs/heads/main/aslookup.c

    - name: Compile C source file
      run: gcc aslookup.c -o aslookup -lcurl -lcjson -lresolv

    - name: Package binary
      run: tar -czvf aslookup.tar.gz aslookup

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: aslookup.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
